Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -27,6 +27,16 @@ jobs:
       - name: Build iOS App
         run: flutter build ios --release --no-codesign
 
+      - name: Debug: List Build Directory
+        run: ls -R build/ios/iphoneos
+
+      - name: Validate Runner.app Exists
+        run: |
+          if [ ! -d "build/ios/iphoneos/Runner.app" ]; then
+            echo "Error: Runner.app not found!"
+            exit 1
+          fi
+
       - name: Prepare Payload Directory
         run: |
           mkdir Payload
